DROP TABLE IF EXISTS person;

CREATE TABLE IF NOT EXISTS person
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(100) NOT NULL,
    birthday_Year INT          NOT NULL
);

INSERT INTO person (name, birthday_year)
VALUES ('Vitaliy', 1988),
       ('Sergey', 1988),
       ('Ola', 2004);

SELECT *
FROM person;

ALTER TABLE person
    ADD COLUMN created_at  TIMESTAMP,
    ADD COLUMN updated_at  TIMESTAMP,
    ADD COLUMN created_who VARCHAR;