DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(100) NOT NULL,
    year_of_birth INT          NOT NULL,
    password      VARCHAR      NOT NULL
);

INSERT INTO users (name, year_of_birth, password)
VALUES ('User1', 1980, 'password1'),
       ('User2', 1980, 'password2');

SELECT * FROM users;
